{% set name = "tape_proteins" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/songlab-cal/tape/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6c65cb58bb941081204cc4a92ed6b15766f6c87489b77f2bdc6afb140ee0a7dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - biopython
    - boto3
    - filelock
    - python-lmdb
    - python >={{ python_min }}
    - requests
    - scipy
    - tensorboardx
    - tqdm
    - pytorch

test:
  imports:
    - tape
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/songlab-cal/tape
  summary: Repostory of Protein Benchmarking and Modeling
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
